Implementação finalizacao de compra parte 2
jorgeluizjava/novo-mercado-livre-api pull request #10
Opened 2020-04-16 04:42 UTC by jorgeluizjava

2020-04-16 11:03 UTC, asouza requested changes
Palmas lentas para você, ficou excelente! Espero que você esteja feliz com o código que produziu. Alguns pequenos detalhes:

* O validador que pega uma compra já processada pode ser generalizado. Pense em como você pode usar uma interface para deixar claro os comportamentos entre os dois objetos de request diferentes. 
* A sua compra não precisa de um atributo status dentro dela. O status da compra é em função de um pagamento realizado com sucesso entre as possíveis várias tentativas. O método registra compra é excelente, mas ali você pode mudar a implementação para operar em cima do conjunto de pagamentos já realizados.

2020-04-16 11:03 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/nova/Compra.java
> +        if (pagamento.comSucesso()) {
e se o pagmento não foi concluido com sucesso :P?

2020-04-16 11:03 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/nova/Compra.java
> +            throw new IllegalArgumentException("Operação inválida, Compra já foi concluída em outro momento.");
bela defesa! é isso! uma chamada deste método para uma compra concluída com sucesso é bug

2020-04-16 11:03 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/retornopagamento/listeners/NotificaErroNovaCompraParaUsuarioListener.java
> +    public int getOrder() {
Por que esse é o 4? Como que alguém batendo o olho aqui vai conseguir entender esse contexto?

2020-04-16 11:03 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/retornopagamento/pagseguro/VerificaSeCompraJaEstaConcluidaPagSeguroValidator.java
> +public class VerificaSeCompraJaEstaConcluidaPagSeguroValidator implements Validator {
Esse validador poderia ser usado para qualquer tipo de retorno né?

2020-04-16 11:52 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/retornopagamento/listeners/NotificaErroNovaCompraParaUsuarioListener.java
> +    public int getOrder() {
Eu pensei em deixar as etapas ordenadas primeiramente os casos de sucesso e depois os de erro. Essa foi a forma mais rápida que encontrei pra ordenar o fluxo.

2020-04-16 11:57 UTC, jorgeluizjava commented
> A sua compra não precisa de um atributo status dentro dela. O status da compra é em função de um pagamento realizado com sucesso entre as possíveis várias tentativas. O método registra compra é excelente, mas ali você pode mudar a implementação para operar em cima do conjunto de pagamentos já realizados.

@asouza eu criei o status na Compra porque na tarefa de "finaliza-compra-parte-1" tem a seguinte necessidade: 

> Uma compra é gerada informando o status INICIADA

Por isso achei que fazia sentido atualizar o status da compra quando um pagamento foi realizado com sucesso.

2020-04-16 12:02 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/nova/Compra.java
> +        if (pagamento.comSucesso()) {
Como estou olhando para o status da compra, quando um pagamento retorna com erro, ele só é registrado e não muda o status da compra.

Neste ponto eu tenho uma dúvida, pra questão de relatórios e consultas, não deveria realmente ter o atributo status na compra? Enfim, aqui poderia acontecer dezenas de coisas hehe

2020-04-16 12:03 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/retornopagamento/pagseguro/VerificaSeCompraJaEstaConcluidaPagSeguroValidator.java
> +public class VerificaSeCompraJaEstaConcluidaPagSeguroValidator implements Validator {
Vou refatorar este validador.

2020-04-16 12:15 UTC, jorgeluizjava commented
@asouza uma das coisas que fiquei com dúvida foi na questão da montagem dos "layouts" das notificações. Antes, em outras notificações você tinha falado pra criar o objeto Email de dentro da classe ProdutoOpiniao e Compra pois a maior parte dos estados já estava dentro destas classes, só que pra fazer as novas notificações não me pareceu certo/legal/sei la oque hehe ter todos os tipos diferentes de notificação dentro da classe compra, por isso deixei os layouts dentro de cada tipo de notificação.

2020-04-17 13:13 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/compra/retornopagamento/pagseguro/VerificaSeCompraJaEstaConcluidaPagSeguroValidator.java
> +public class VerificaSeCompraJaEstaConcluidaPagSeguroValidator implements Validator {
Refatorei! 😃

2020-06-23 10:52 UTC, merged