Implementação da funcionalidade pergunta ao vendedor
jorgeluizjava/novo-mercado-livre-api pull request #6
Opened 2020-04-02 13:51 UTC by jorgeluizjava

2020-04-03 11:18 UTC, asouza requested changes

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPergunta.java
> +    public String getLinkDetalheProduto(UriComponentsBuilder uriComponentsBuilder) {
Eu gosto deste código! Mas eu preciso de deixar alerta que algumas pessoas talvez te critiquem aqui. O review pode ser parecido com esse aqui:

_Pessoa_: Como assim você passou  o uriComponentsBuilder para o model?
Jorge: Passei ué. Quero gerar uma coisa em função do estado da pergunta. 
_Pessoa_: Mas como que o produtoPergunta sabe qual é a rota do link? Isso não é **responsabilidade** dessa classe. Ela não devia saber nem a rota nem ter contato com o Spring. 
Jorge: Por que? Se isso ficasse em outra classe qual seria a vantagem?
_Pessoa_: Você deixaria a coisa desacoplada... 
Jorge: Desacoplada de que... Por que desse jeito que você ta sugerindo é melhor?

Aí a pessoa bugou e você percebe que o argumento volta no loop. Se alguém te der um argumento realmente interessante, me avisa, tudo bem? Estamos sempre abertos a mudar de ideia.

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaRequest.java
> +    public ProdutoPergunta criaProdutoPergunta(Produto produto, Usuario usuarioLogado) {
Sério, você ta brocando!

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaRequest.java
> +    public ProdutoPergunta criaProdutoPergunta(Produto produto, Usuario usuarioLogado) {
Uma pessoa que está brocando significa que está mandando muito bem :)

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +        String de = produtoPergunta.getEmailUsuario();
Boa parte da informação desta notificação é gerada em função do estado de um produtoPergunta. Por que não temos um método lá que possa construir essa notificação? A classe Email está ok para mim :).

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +public class ProdutoPerguntaService {
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

O nome ProdutoPerguntaService não traz nenhum entendimento sobre a ação do sistema. Lembra que esse tipo de classe conversa com um caso de uso, ou parte dele. A parte do caso de uso aqui é: NotificaDonoDoProduto :)

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutosController.java
> +    @Autowired
Aqui cai justamente naquela ideia que eu tava formando ontem. Você acabou de ter um controller que perdeu 100% de coesão. Cada método usa dependências completamente diferentes...

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +public class ProdutoPerguntaService {
E aí em vez de colocar a semântica no nome do método, você coloca no nome da classe. Dessa forma você aumenta chance de gerar um incomodo em alguém que queira meter mais um método aqui, quebrando os 100% de coesão.

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +public class ProdutoPerguntaService {
O nome do método pode ser ```executa``` por exemplo.

2020-04-03 11:18 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +        String de = produtoPergunta.getEmailUsuario();
O objeto que representa o email é construído inteiramente em função do estado da pergunta. E é um objeto que faz parte de um caso de uso da aplicação.

2020-04-04 12:07 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutosController.java
> +    @Autowired
Alberto eu refatorei e criei Controllers de acordo com a funcionalidade.

2020-04-04 12:09 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +public class ProdutoPerguntaService {
Rafatorei essa parte também.

2020-04-04 12:10 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaService.java
> +        String de = produtoPergunta.getEmailUsuario();
Nesse caso eu criei o método para construir um Email dentro da classe  produtoPergunta.

Tive um monte de dúvidas hehe
Fiquei pensando, crio uma classe Notificação, passo os valores pra ela e nela eu crio um Email... pensei, pensei e não fiz assim hehehe.

2020-04-04 12:15 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/ProdutoPerguntaRequest.java
> +    public ProdutoPergunta criaProdutoPergunta(Produto produto, Usuario usuarioLogado) {
Valeu hehehe

2020-04-04 21:27 UTC, asouza approved these changes

2020-04-04 21:49 UTC, merged