Implementação dos detalhes do produto
jorgeluizjava/novo-mercado-livre-api pull request #8
Opened 2020-04-05 20:03 UTC by jorgeluizjava

2020-04-06 10:06 UTC, asouza requested changes
Mandou super bem! Dificuldade espalhada entre as várias classes necessárias para montar aquela tela. Além do desafio que deixei, pelo que vi ainda faltam algumas coisas. 

* Exibir as opiniões sobre o produto, informando inclusive uma média entre elas.
* As perguntas devem vir ordenadas da última para a primeira.

2020-04-06 10:06 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/NossoMercadoLivreApiApplication.java
> +		categoriaRepository.save(tecnologia);
O banco roda em memória? Eu não lembro agora... Esse código vai rodar em cada restart né?

2020-04-06 10:06 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Foto.java
>      @JoinColumn(name = "produto_id")
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Aqui já é o comportamento default. Adicionou por algum motivo específico?

2020-04-06 10:06 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +        while (categoria != null) {
*Não retornamos nulo dentro das regras da aplicação. Pense que seu computador vai explodir.*

2020-04-06 10:06 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +        while (categoria != null) {
Aqui dentro você tem um código que mistura manipulação da hierarquia de categorias com um código específico do DTO em si. Seu desafio é deixar o código que manipula o objeto dentro do o objeto e o código do DTO no DTO. Aqui você tem while, !=null e reatribuição de variável. No final ainda tem um reverse :). 

*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*
Se você tem uma lista, e da uma reverse no final, o que você quer é uma pilha. Pode usar a classe Stack do Java.

2020-04-06 10:06 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +        return produtoPergutaRepository
Pq você não fez uso do bidirecional aqui? Poderia mapear as perguntas lá no produto e chamar o método que retornava o conjunto.

2020-04-06 10:06 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/shared/URLValidator.java
> +public class URLValidator {
Mandou bem aqui!

2020-04-06 10:19 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/NossoMercadoLivreApiApplication.java
> +		categoriaRepository.save(tecnologia);
Isso mesmo.
Eu estava perdendo muito tempo carregando essas categorias hehe
Vou fazer pra usuário e produto também 😄

2020-04-06 23:32 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Foto.java
>      @JoinColumn(name = "produto_id")
Eu usei essa anotação pois o nome da coluna estava ficando como "produto_produto_id" e eu queria "produto_id". 😃

2020-04-07 01:04 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +        while (categoria != null) {
Alberto dividi a responsabilidade com a classe Produto e ProdutoDetalheDTO, a classe Produto fica responsável pelo retorno das Categorias e a ProdutoDetalheDTO em fazer a conversão.

Quanto ao null é porque na hierarquia de Categorias a Categoria Mãe não é obrigatória.

Implementei usando a classe Stack, mas dessa nova maneira eu poderia ter retornado um List na classe Produto e na hora da conversão dar um reverse? Funcionaria também né?

Mas entendi sua motivação hehe.

2020-04-07 01:04 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +        return produtoPergutaRepository
Implementei o bidirecional nas entidades, facilitou bastante.

2020-04-07 18:22 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Foto.java
>      @JoinColumn(name = "produto_id")
engraçado isso... o id no produto chama produtoId?

2020-04-07 18:23 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +        while (categoria != null) {
Funcionar, funcionaria. Por outro lado a pergunta que você deve se fazer é como alguém ia saber que precisava chamar o reverse.

2020-04-07 21:22 UTC, asouza requested changes
Eu não vou aprovar pq neste estágio precisamos maximizar a exploração do código :)

2020-04-07 21:22 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    @OneToMany(mappedBy = "produto", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
*A versão mais eficiente de uma pessoa programando é aquela que questiona e implementa estritamente o que foi descrito. Não inventamos coisas que não foram pedidas, não fazemos suposição de funcionalidade e nem caímos na armadilha de achar que entendemos mais do que a pessoa que solicitou a funcionalidade.*

Uma remoção aqui é algo mais sério. As perguntas tem um valor para o mercado livre...  mesmo a remoção de produto não é algo que a gente pensou ... não imagino que a gente remover realmente e sim desabilitar. Manda o mapeamento, mas só precisa deixar mapeado o cascateamento de persist :).

2020-04-07 21:22 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public List<ProdutoPergunta> getPerguntasEmOrdemDeDataDecrescente() {
Este método conversa com o propósito de métodos nas nossas classes que mantém estado do sistema, sem dúvidas. Por outro lado, você precisaria de um método diferente para cada tipo de exibição de perguntas do sistema.  Por mais que agora você não tenha, vou deixar uma sugestão. 

Você pode deixar aqui o método mais genérico que receba uma função de ordenação como argumento :). vou deixar como desafio.

2020-04-07 21:22 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public Stack<Categoria> getCategorias() {
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

Aqui realmente é complicado de entender como que é a organização dessas categorias que estão sendo retornadas. Essa pilha tem como primeiro elemento a categoria raiz ou a folha? Qual pista você deixar aqui? Será que você pode parametrizar?

2020-04-08 12:22 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    @OneToMany(mappedBy = "produto", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
Alberto coloquei o Cascade.PERSIST e removi o orphanRemoval.
Não implementei a questão do produto ativo/inativo, é para implementar?

2020-04-08 13:17 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public List<ProdutoPergunta> getPerguntasEmOrdemDeDataDecrescente() {
Alberto não sei se era isso que você estava imaginando mas a maneira que consegui foi deixar a assinatura do método assim: ```public List<ProdutoPergunta> getPerguntas(Comparator<ProdutoPergunta> comparator)```
e quem chama o método é quem decide como quer que o método se comporte.

2020-04-08 13:50 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public Stack<Categoria> getCategorias() {
A única coisa que consegui imaginar foi colocar um parâmetro boleano para distinguir qual ordem o método deve retornar.

2020-04-08 14:03 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public Stack<Categoria> getCategorias() {
Nessas coisas eu realmente fico bem indeciso.

2020-04-09 09:11 UTC, asouza approved these changes
Aqui eu deixei vários mini pontos, mas nenhum que considero blocante.

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/categoria/OrdenacaoCategoria.java
> +public class OrdenacaoCategoria {
Era isso mesmo. Para este tipo de classe, você pode usar uma enum :). Ordenacao.MAE_PARA_FILHA e Ordenacao.FILHA_PARA_MAE ou qualquer nome que você entendesse legal :).

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
>      @OneToMany(mappedBy = "produto", cascade = CascadeType.ALL, orphanRemoval = true)
pode deixar o cascade.persist para tudo aqui.

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
>      private List<Caracteristica> caracteristicas = new ArrayList<>();
Um ponto para reflexão. Todas essas List que você declarou deveriam ser Set. Nada aí é repetido :).

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +        perguntas.sort(comparator);
aqui eu acho que você não deve usar o .sort da List, ele altera a ordenação real dos elementos dentro da coleção e não é isso que você quer :). Manda um .stream() e cria uma nova versão da coleção ordenada. Pensando no parâmetro, era isso mesmo :).

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public Stack<Categoria> getCategorias(OrdenacaoCategoria ordenacaoCategoria) {
Pronto, agora com o parâmetro você pode até voltar a generalizar o retorno aqui :). Pode ser uma List mesmo, já que o parâmetro já indica o critério de montagem da sequência.

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public List<ProdutoOpiniao> getOpinioes() {
Quando você vai retornar coleções que são gerenciadas pelo Hibernate tende a ser uma boa defesa você retornar uma versão imutável da coleção, ainda mais se sua coleção ta mapeada com alguma operação de cascata.

2020-04-09 09:11 UTC, asouza commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +    private Stack<CategoriaProdutoDetalheDTO> extraiCategorias(Produto produto, UriComponentsBuilder uriComponentsBuilder) {
Dava para resumir o método agora retornando uma List e aplicando um map no retorno da coleção do getCategorias ne?

2020-04-09 10:19 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/categoria/OrdenacaoCategoria.java
> +public class OrdenacaoCategoria {
Refiz da maneira que você sugeriu.

2020-04-09 10:19 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
>      @OneToMany(mappedBy = "produto", cascade = CascadeType.ALL, orphanRemoval = true)
Refiz da maneira que você sugeriu.

2020-04-09 10:21 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
>      private List<Caracteristica> caracteristicas = new ArrayList<>();
Refiz apenas da caracteristica e da foto, eu não achei nenhuma restrição nos cards por isso mandei bala no List hehehe.

2020-04-09 10:21 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +        perguntas.sort(comparator);
Refiz da maneira que você sugeriu.

2020-04-09 10:23 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public Stack<Categoria> getCategorias(OrdenacaoCategoria ordenacaoCategoria) {
Refiz da maneira que você sugeriu.

2020-04-09 10:23 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/Produto.java
> +    public List<ProdutoOpiniao> getOpinioes() {
Refiz da maneira que você sugeriu.

2020-04-09 10:23 UTC, jorgeluizjava commented on src/main/java/br/com/deveficiente/nossomercadolivreapi/produto/detalhe/ProdutoDetalheDTO.java
> +    private Stack<CategoriaProdutoDetalheDTO> extraiCategorias(Produto produto, UriComponentsBuilder uriComponentsBuilder) {
Refiz da maneira que você sugeriu.

2020-04-09 10:26 UTC, merged